import psutil
import time
import os
from datetime import datetime

# ── Configuration ─────────────────────────────────────
CPU_THRESHOLD = 85        # % — alert if CPU exceeds this
RAM_THRESHOLD = 80        # % — alert if RAM exceeds this
DISK_THRESHOLD = 70       # % — alert if Disk exceeds this
CHECK_INTERVAL = 5        # seconds between each check
INCIDENT_COUNT = 3        # consecutive breaches = incident

LOG_DIR = "logs"
REPORT_DIR = "reports"

# ── Helpers ───────────────────────────────────────────
def get_timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def get_log_filename():
    return os.path.join(LOG_DIR, f"sysguard_{datetime.now().strftime('%Y-%m-%d')}.log")

def log(message, level="INFO"):
    timestamp = get_timestamp()
    line = f"[{timestamp}] [{level}] {message}"
    print(line)
    with open(get_log_filename(), "a") as f:
        f.write(line + "\n")

# ── Metric Collection ─────────────────────────────────
def collect_metrics():
    cpu = psutil.cpu_percent(interval=1)
    ram = psutil.virtual_memory().percent
    disk = psutil.disk_usage('/').percent
    net = psutil.net_io_counters()
    net_sent_mb = round(net.bytes_sent / (1024 * 1024), 2)
    net_recv_mb = round(net.bytes_recv / (1024 * 1024), 2)
    return {
        "cpu": cpu,
        "ram": ram,
        "disk": disk,
        "net_sent_mb": net_sent_mb,
        "net_recv_mb": net_recv_mb,
        "timestamp": get_timestamp()
    }

# ── Anomaly Detection ─────────────────────────────────
def check_anomalies(metrics):
    anomalies = []
    if metrics["cpu"] > CPU_THRESHOLD:
        anomalies.append(("CPU", metrics["cpu"], CPU_THRESHOLD))
    if metrics["ram"] > RAM_THRESHOLD:
        anomalies.append(("RAM", metrics["ram"], RAM_THRESHOLD))
    if metrics["disk"] > DISK_THRESHOLD:
        anomalies.append(("DISK", metrics["disk"], DISK_THRESHOLD))
    return anomalies

# ── RCA Report Generator ──────────────────────────────
def generate_rca(incident_log):
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = os.path.join(REPORT_DIR, f"RCA_INCIDENT_{timestamp}.txt")

    # Build probable cause
    metrics_involved = list(set([i["metric"] for i in incident_log]))
    probable_cause = []
    if "CPU" in metrics_involved:
        probable_cause.append("High CPU — possible runaway process or resource-intensive task")
    if "RAM" in metrics_involved:
        probable_cause.append("High RAM — possible memory leak or excessive application load")
    if "DISK" in metrics_involved:
        probable_cause.append("High Disk — possible log accumulation or large file writes")

    first_time = incident_log[0]["time"]
    last_time = incident_log[-1]["time"]
    peak_values = {}
    for entry in incident_log:
        m = entry["metric"]
        if m not in peak_values or entry["value"] > peak_values[m]:
            peak_values[m] = entry["value"]

    rca_content = f"""
╔══════════════════════════════════════════════════════════╗
         INCIDENT ROOT CAUSE ANALYSIS REPORT
╚══════════════════════════════════════════════════════════╝

Project         : SysGuard — Automated System Health Monitor
Generated By    : Anwesha Sahoo
Generated At    : {get_timestamp()}
Incident ID     : INC-{timestamp}
Severity        : HIGH

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. INCIDENT SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SysGuard detected sustained threshold breaches across the
following metrics: {", ".join(metrics_involved)}
The anomaly persisted for {len(incident_log)} consecutive
monitoring cycles ({len(incident_log) * CHECK_INTERVAL} seconds total).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2. INCIDENT TIMELINE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{first_time}  — First anomaly detected by SysGuard
{first_time}  — Alert triggered, incident logging started
{last_time}   — Final anomaly reading recorded
{get_timestamp()}  — RCA report auto-generated

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
3. METRICS AT TIME OF INCIDENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{"".join([f"  {m:<6} Peak Value : {v}%   Threshold : {CPU_THRESHOLD if m == 'CPU' else RAM_THRESHOLD if m == 'RAM' else DISK_THRESHOLD}%{chr(10)}" for m, v in peak_values.items()])}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
4. ROOT CAUSE ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{"".join([f"  → {c}{chr(10)}" for c in probable_cause])}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
5. IMPACT ASSESSMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Duration        : {len(incident_log) * CHECK_INTERVAL} seconds
  Metrics Affected: {", ".join(metrics_involved)}
  Monitoring Cycles Breached: {len(incident_log)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
6. RESOLUTION STEPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  1. Identified offending process via: ps aux --sort=-%cpu
  2. Investigated memory usage via: vm_stat / top
  3. Terminated or optimised the resource-intensive process
  4. Confirmed metrics returned below threshold
  5. Reviewed logs in /logs for pattern analysis

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
7. PREVENTIVE MEASURES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  → Lower alert thresholds for earlier detection
  → Schedule automated restarts for memory-leaking services
  → Integrate with PagerDuty / Slack for real-time alerting
  → Set up log rotation to prevent disk exhaustion
  → Run SysGuard as a background daemon via cron/systemd

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
8. LESSONS LEARNED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  → Automated monitoring catches issues faster than manual checks
  → Consecutive-reading logic reduces false positives significantly
  → Structured RCA documentation accelerates future resolutions

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
         END OF REPORT — Generated by SysGuard v1.0
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    with open(filename, "w") as f:
        f.write(rca_content)
    log(f"RCA Report generated → {filename}", "REPORT")
    return filename

# ── Main Monitor Loop ─────────────────────────────────
def run_monitor():
    log("=" * 55)
    log("SysGuard v1.0 — System Health Monitor STARTED")
    log(f"Thresholds → CPU:{CPU_THRESHOLD}% | RAM:{RAM_THRESHOLD}% | DISK:{DISK_THRESHOLD}%")
    log("=" * 55)

    consecutive_breach = {}   # metric -> count
    incident_log = []
    incident_active = False

    try:
        while True:
            metrics = collect_metrics()

            log(f"CPU: {metrics['cpu']}% | RAM: {metrics['ram']}% | "
                f"DISK: {metrics['disk']}% | "
                f"NET ↑{metrics['net_sent_mb']}MB ↓{metrics['net_recv_mb']}MB")

            anomalies = check_anomalies(metrics)

            if anomalies:
                for metric, value, threshold in anomalies:
                    consecutive_breach[metric] = consecutive_breach.get(metric, 0) + 1
                    log(f"⚠ WARNING — {metric} at {value}% "
                        f"(threshold: {threshold}%) "
                        f"[breach #{consecutive_breach[metric]}]", "WARN")

                    if consecutive_breach[metric] >= INCIDENT_COUNT:
                        if not incident_active:
                            log(f"🚨 INCIDENT DECLARED — {metric} breach sustained "
                                f"for {INCIDENT_COUNT} consecutive readings", "CRITICAL")
                            incident_active = True
                        incident_log.append({
                            "metric": metric,
                            "value": value,
                            "time": get_timestamp()
                        })
            else:
                # Reset breach counters when metrics normalise
                if incident_active and incident_log:
                    log("✅ Metrics normalised — generating RCA report...", "INFO")
                    rca_file = generate_rca(incident_log)
                    log(f"✅ RCA saved → {rca_file}", "INFO")
                    incident_log = []
                    incident_active = False
                consecutive_breach = {}

            time.sleep(CHECK_INTERVAL)

    except KeyboardInterrupt:
        log("SysGuard stopped by user.")
        if incident_log:
            log("Incident was active — generating final RCA before exit...", "WARN")
            generate_rca(incident_log)

if __name__ == "__main__":
    run_monitor()